import json
NE="No verified email"
def R(**k):
    base={"company":"","website":"","shopify_store_url":"","country":"United States","state":"","city":"","industry":"","product_category":"","company_size":"Not verified","prospect_name":"","first_name":"","job_title":"","contact_source_url":"","email":"","email_source_url":"","email_note":"","shopify_verified":"","shopify_evidence":"","shopify_evidence_url":"","shopify_plus":"Not verified","shopify_plus_evidence":"","product_count_signal":"Not verified","shopify_apps":"Not verified","operational_signal":"","automation_opportunity":"","buying_intent":"","personalization_detail":"","personalization_reason":"","source_urls":[],"evidence_type":"","research_confidence":"","notes":""}
    base.update(k)
    if not base["email"] and not base["email_note"]: base["email_note"]=NE
    return base
recs=[
R(company="Gnarly Nutrition",website="https://gognarly.com",shopify_store_url="https://gnarly-nutrition.myshopify.com",state="Utah",city="Salt Lake City",industry="Sports nutrition",product_category="Protein powders, pre-workout, hydration, vitamins",
 prospect_name="Eli Kerr",first_name="Eli",job_title="Co-founder & CEO",contact_source_url="https://business.utah.gov/in-their-words/in-their-words-eli-kerr/",
 shopify_verified="Yes",shopify_evidence="gnarly-nutrition.myshopify.com collection URL appears in search results; Refindable Shopify partner case study",shopify_evidence_url="https://gnarly-nutrition.myshopify.com/collections/all/performance",
 shopify_plus_evidence="Brand profile summary (internetresearchunit.com) says it is on Shopify Plus; no Shopify/agency Plus case study seen",
 shopify_apps="Recharge (case study)",operational_signal="Recharge subscriptions with tiered loyalty discounts; SMS-based subscription management; DTC plus Amazon listing; USA Climbing nutrition sponsor since 2019",
 automation_opportunity="Potential opportunity: syncing subscription-tier status and SMS subscription changes with fulfillment and customer-service workflows",
 buying_intent="Medium",personalization_detail="Doubled customer LTV after launching Recharge subscriptions with tiered rewards; over 25% of subscribers reached the third tier (20% off)",
 personalization_reason="Tiered subscription logic plus SMS order edits creates recurring operational events that benefit from automation",
 source_urls=["https://getrecharge.com/case-studies/gnarly-nutrition-doubled-customer-ltv-with-subscriptions/","https://gnarly-nutrition.myshopify.com/collections/all/performance","https://gognarly.com/","https://refindable.com/project/case-study-gnarly-shopify/","https://internetresearchunit.com/brands/gnarly-nutrition","https://business.utah.gov/in-their-words/in-their-words-eli-kerr/","https://gognarly.com/pages/contact-us"],
 evidence_type="myshopify domain; Recharge case study; Agency case study; Government profile",research_confidence="High",notes="Phone +1 (855) 406-0959 surfaced in search; no public generic email seen. Founding year cited as 2012/2013 in different sources."),
R(company="Death Wish Coffee",website="https://www.deathwishcoffee.com",shopify_store_url="https://www.deathwishcoffee.com",industry="Coffee",product_category="Coffee (ground, whole bean, pods), merch",
 prospect_name="Mike Brown",first_name="Mike",job_title="Founder (per Blue Stout podcast interview)",contact_source_url="https://bluestout.com/ecommerce/mike-brown-death-wish-coffee-ecommerce-brand-building-podcast-interview/",
 email="hey@deathwishcoffee.com",email_source_url="https://www.deathwishcoffee.com/pages/help",email_note="Customer service inbox surfaced in search summary for help/contact query (sources included help page and pissedconsumer)",
 shopify_verified="Yes",shopify_evidence="Official Shopify Plus customer story and case study",shopify_evidence_url="https://www.shopify.com/case-studies/death-wish-coffee",
 shopify_plus="Yes",shopify_plus_evidence="Shopify Plus customer page: Death Wish Coffee integrated its ERP with Shopify Plus",
 operational_signal="ERP integrated with Shopify Plus; inventory across own warehouse, 3PLs and a distribution center; multichannel selling; separate wholesale site (dwccwholesale.com); subscription platform migration (Commence Studio); retail at Walmart",
 automation_opportunity="Potential opportunity: automating multi-location inventory reconciliation and wholesale order routing across DTC, wholesale and retail channels",
 buying_intent="High",personalization_detail="Handled 150,000+ Super Bowl visitors and $2,083/minute in sales after replatforming to Shopify Plus with ERP integration across multiple warehouses",
 personalization_reason="Inventory spread across own warehouse, 3PLs and a DC makes cross-system automation directly relevant",
 source_urls=["https://www.shopify.com/case-studies/death-wish-coffee","https://www.shopify.com/au/plus/customers/death-wish-coffee","https://www.shopify.com/enterprise/blog/how-death-wish-coffee-made-2-083-a-minute-an-awkward-moment-with-mom-by-winning-the-super-bowl","https://bluestout.com/ecommerce/mike-brown-death-wish-coffee-ecommerce-brand-building-podcast-interview/","https://commence.studio/work/shopify-coffee-subscription-migration-cro/","https://www.deathwishcoffee.com/pages/help","https://www.dwccwholesale.com/pages/contact-us","https://www.walmart.com/c/kp/death-wish"],
 evidence_type="Shopify Plus case study; Agency case study; Podcast interview",research_confidence="High",notes="Verify Mike Brown's current role before outreach. Beware lookalike domains (deathwishcoffees.co) in search results."),
R(company="Magic Spoon",website="https://magicspoon.com",shopify_store_url="https://magicspoon.com",industry="Food & beverage",product_category="High-protein cereal, treats, granola",
 prospect_name="Gabi Lewis",first_name="Gabi",job_title="Co-founder",contact_source_url="https://contactout.com/Gabi-Lewis-516344",
 email="hello@magicspoon.com",email_source_url="https://magicspoon.com/pages/contact",email_note="Also support@magicspoon.com surfaced in same search",
 shopify_verified="Yes",shopify_evidence="Official Shopify case study for Magic Spoon",shopify_evidence_url="https://shopify.com/case-studies/magic-spoon",
 shopify_plus_evidence="Shopify case study exists but Plus tier not explicitly stated in results seen",
 shopify_apps="Rebuy (Smart Cart case study)",operational_signal="Subscriptions (29% increase in opt-ins); custom bundle page rebuilt on Shopify 2.0; seven-figure TikTok Shop channel; checkout-level upsells; expanded from cereal to treats and granola",
 automation_opportunity="Potential opportunity: automating custom bundle and subscription order handling across Shopify DTC and TikTok Shop",
 buying_intent="Medium",personalization_detail="Scaled TikTok Shop into a seven-figure channel and rebuilt its custom bundle builder on Shopify 2.0",
 personalization_reason="Multi-channel orders (DTC + TikTok Shop) with custom bundles increase order-ops complexity",
 source_urls=["https://shopify.com/case-studies/magic-spoon","https://www.rebuyengine.com/case-studies/magic-spoon","https://magicspoon.com/pages/contact","https://contactout.com/Gabi-Lewis-516344","https://en.wikipedia.org/wiki/Magic_Spoon"],
 evidence_type="Shopify case study; App vendor case study",research_confidence="High",notes="Rebuy Smart Cart boosted AOV 14.75%."),
R(company="OLIPOP",website="https://drinkolipop.com",shopify_store_url="https://drinkolipop.com",industry="Beverage",product_category="Prebiotic soda",
 prospect_name="Ben Goodwin",first_name="Ben",job_title="Co-founder (former CEO; stepped down, successor Christian Patino Webb)",contact_source_url="https://www.inc.com/victoria-salves/olipop-founder-stepping-down-as-ceo-not-stepping-away-from-the-brand/91389615",
 email="hello@drinkolipop.com",email_source_url="https://drinkolipop.com/pages/contact-us",email_note="Surfaced in search summary for contact query; results also included lookalike domains, so confirm on official contact page",
 shopify_verified="Yes",shopify_evidence="Presidio subscription-optimization client story on Shopify Plus; Shopify blog feature; Commerce Caffeine tech stack",shopify_evidence_url="https://presidiodev.com/our-work/olipop",
 shopify_plus="Yes",shopify_plus_evidence="Agency client story (Presidio) describes Olipop's Shopify Plus DTC engine",
 shopify_apps="Gorgias (Gorgias blog with Olipop's Eli Weiss)",operational_signal="Subscription program; volume-based AOV incentives; flavor launches; national retail expansion alongside DTC; ~$1.85B valuation",
 automation_opportunity="Potential opportunity: automating subscription-change and CX ticket workflows as DTC shifts toward a retention channel",
 buying_intent="Medium",personalization_detail="Repositioned DTC as a retention/LTV channel with subscription optimization and volume incentives while expanding national retail",
 personalization_reason="High-volume subscription base and CX (Gorgias) operations benefit from workflow automation",
 source_urls=["https://presidiodev.com/our-work/olipop","https://www.shopify.com/blog/olipop-product-development","https://www.gorgias.com/blog/olipop-sms","https://www.commercecaffeine.com/brands/olipop","https://drinkolipop.com/pages/contact-us","https://www.inc.com/victoria-salves/olipop-founder-stepping-down-as-ceo-not-stepping-away-from-the-brand/91389615","https://karagoldin.com/podcasts/ben-goodwin/"],
 evidence_type="Agency case study; Shopify blog; App vendor blog; Press",research_confidence="High",notes="Current CEO Christian Patino Webb per Inc. summary; consider targeting ecommerce lead instead."),
R(company="Bloom Nutrition",website="https://bloomnu.com",shopify_store_url="https://bloomnu.com",state="California",city="Venice",industry="Supplements",product_category="Greens powders, energy drinks, women's wellness supplements",
 prospect_name="Mari Llewellyn",first_name="Mari",job_title="Founder",contact_source_url="https://storeinspect.com/shopify-store/bloom-nutrition",
 email="help@bloomnu.com",email_source_url="https://bloomnu.com/pages/contact-us",email_note="Customer service inbox surfaced in search summary for contact query",
 shopify_verified="Yes",shopify_evidence="StoreInspect tech profile: bloomnu.com uses Shopify Plus",shopify_evidence_url="https://storeinspect.com/shopify-store/bloom-nutrition",
 shopify_plus_evidence="Tech profile (StoreInspect) reports Shopify Plus; no Shopify/agency Plus case study seen",
 shopify_apps="Okendo, Klaviyo, Attentive (StoreInspect / DTC Newsletter)",operational_signal="~505K monthly visits; shoppable TikTok UGC on PDPs; Bloom Sparkling Energy beverage line; high recurring-revenue model cited",
 automation_opportunity="Potential opportunity: connecting Okendo reviews, Klaviyo and Attentive signals to automate post-purchase and replenishment flows",
 buying_intent="Medium",personalization_detail="Embeds shoppable TikTok UGC videos on homepage and product pages; ~505K monthly site visits",
 personalization_reason="High traffic and multi-app stack mean many cross-tool data handoffs",
 source_urls=["https://storeinspect.com/shopify-store/bloom-nutrition","https://www.directtoconsumer.co/newsletter/dtc899-bloom-nutrition-tech-stack-scale-like-a-billion-dollar-brand-and-pricing-perception","https://brandsearch.co/brands/bloomnu.com","https://bloomnu.com/pages/contact-us","https://en.wikipedia.org/wiki/Bloom_Sparkling_Energy"],
 evidence_type="Tech profile; Newsletter",research_confidence="Medium",notes="Corporate PO Box in Venice, CA per search summary."),
R(company="Momentous",website="https://www.livemomentous.com",shopify_store_url="https://www.livemomentous.com",state="Utah",city="Park City",industry="Sports nutrition / supplements",product_category="Protein, creatine, performance and health supplements",
 prospect_name="Jeff Byers",first_name="Jeff",job_title="Co-founder & CEO",contact_source_url="https://www.linkedin.com/in/jeffbyersceo/",
 shopify_verified="Likely",shopify_evidence="Design/development case study by Shopify Plus agency Anatta; storefront uses /pages/ and /blogs/ paths; listed in Shopify Plus supplement brand roundups",shopify_evidence_url="https://anatta.io/case-study/momentous",
 shopify_plus_evidence="Appears in third-party 'DTC supplement brands on Shopify Plus' list (getmore.mx); not an official case study",
 operational_signal="Subscribe & save 15%; 60-80% recurring revenue cited; supplies ~200 pro/college teams; DoD contracts; expanded into 640+ Vitamin Shoppe stores (Jan 2026); NSF/Informed Sport certified",
 automation_opportunity="Potential opportunity: automating B2B team/institutional orders alongside DTC subscriptions and retail replenishment",
 buying_intent="High",personalization_detail="Sells to ~200 professional and collegiate teams plus DoD, while running DTC subscriptions and a 640+ store Vitamin Shoppe rollout",
 personalization_reason="Parallel B2B, retail and subscription channels create order-routing and reporting complexity",
 source_urls=["https://anatta.io/case-study/momentous","https://getmore.mx/en-us/blogs/ecommerce-con-shopify/top-marcas-suplementos-dtc-shopify-plus","https://www.dtcpatterns.com/dtc-patterns-articles/momentous-keeps-customers-coming-back-for-more-with-their-subscription-program","https://help.livemomentous.com/hc/en-us/articles/19199710473875-How-do-I-contact-Momentous-Customer-Care","https://www.linkedin.com/in/jeffbyersceo/","https://athletechnews.com/ceo-corner-momentous-jeff-byers-exclusive-interview/","https://www.livemomentous.com/pages/press-inquiries"],
 evidence_type="Agency case study; Shopify URL patterns; Press",research_confidence="Medium",notes="Support via contact page/chat and +1.800.357.8714; address 1526 Ute Blvd Ste 214, Park City UT."),
R(company="Athletic Brewing Company",website="https://athleticbrewing.com",shopify_store_url="https://athleticbrewing.com",industry="Beverage",product_category="Non-alcoholic craft beer",
 prospect_name="Bill Shufelt",first_name="Bill",job_title="Founder",contact_source_url="https://storeinspect.com/shopify-store/athletic-brewing",
 email="info@athleticbrewing.com",email_source_url="https://help.athleticbrewing.com/en-US/contact-us-855678",email_note="Customer service inbox surfaced in search summary for contact query",
 shopify_verified="Yes",shopify_evidence="StoreInspect Shopify profile for athleticbrewing.com; /pages/help-center path",shopify_evidence_url="https://storeinspect.com/shopify-store/athletic-brewing",
 shopify_plus_evidence="Tech profile reports Shopify Plus; no official Plus case study seen",
 operational_signal="~750K monthly visitors; mobile app (Wonderful); wholesale/B2B online sales (HubSpot case study PDF); $75M Series D ($225M total) incl. Keurig Dr Pepper stake",
 automation_opportunity="Potential opportunity: unifying DTC, app and wholesale/B2B order data into automated fulfillment and CX workflows",
 buying_intent="Medium",personalization_detail="Expanded online sales to cover wholesale/B2B use cases and runs a dedicated mobile app for superusers",
 personalization_reason="Multiple ordering surfaces (web, app, wholesale) benefit from automated sync",
 source_urls=["https://storeinspect.com/shopify-store/athletic-brewing","https://wonderful.io/work/athletic-brewing-company/","https://cdn2.hubspot.net/hubfs/425453/Athletic%20Brewing%20Case%20Study.pdf","https://help.athleticbrewing.com/en-US/contact-us-855678","https://athleticbrewing.com/pages/help-center","https://www.omnisend.com/blog/shopify-food-and-beverage-stores/"],
 evidence_type="Tech profile; Agency case study",research_confidence="Medium",notes="Alcohol-adjacent shipping rules may apply by state."),
R(company="Chamberlain Coffee",website="https://chamberlaincoffee.com",shopify_store_url="https://chamberlaincoffee.com",industry="Coffee",product_category="Coffee, cold brew, matcha, accessories, merch",
 prospect_name="Emma Chamberlain",first_name="Emma",job_title="Founder",contact_source_url="https://www.facebook.com/shopify/posts/find-out-why-emma-used-shopify-to-start-chamberlain-coffee-/1276104221215633/",
 email="hi@chamberlaincoffee.com",email_source_url="https://chamberlaincoffee.com/pages/contact",email_note="Customer service inbox surfaced in search summary",
 shopify_verified="Yes",shopify_evidence="Shopify original series 'Behind the Brew' with Chamberlain Coffee; brand says it was built on Shopify from first sale",shopify_evidence_url="https://www.tiktok.com/@chamberlaincoffee/video/7526970747416251661",
 shopify_apps="Gorgias (help center at chamberlaincoffee.gorgias.help)",operational_signal="Separate EU storefront (chamberlaincoffee.eu); coffee, matcha and accessories catalog; Gorgias help center",
 automation_opportunity="Potential opportunity: coordinating order and support workflows across US and EU storefronts",
 buying_intent="Low",personalization_detail="Operates a separate EU storefront (chamberlaincoffee.eu) alongside the US store",
 personalization_reason="Multi-storefront operations create duplicated catalog and CX tasks",
 source_urls=["https://chamberlaincoffee.com/","https://chamberlaincoffee.com/pages/contact","https://chamberlaincoffee.eu/pages/contact","https://chamberlaincoffee.gorgias.help/en-US/contact","https://www.tiktok.com/@chamberlaincoffee/video/7526970747416251661","https://analyzify.com/shopify-stores/chamberlain-coffee","https://rocketreach.co/jeumana-jaber-email_68765137"],
 evidence_type="Shopify partnership content; Tech profile; Help center",research_confidence="Medium",notes="RocketReach lists Jeumana Jaber as CMO (alternative contact; verify)."),
R(company="Transparent Labs",website="https://www.transparentlabs.com",shopify_store_url="https://www.transparentlabs.com",state="Utah",city="Lindon",industry="Sports nutrition",product_category="Protein, pre-workout, creatine, supplements",
 email="support@transparentlabs.com",email_source_url="https://www.transparentlabs.com/pages/contact-us",email_note="Support inbox surfaced in search summary for contact query",
 shopify_verified="Yes",shopify_evidence="XgenTech (Shopify Partner) case study: built the original Transparent Labs Shopify Plus theme",shopify_evidence_url="https://xgentech.net/blogs/our-work/transparent-labs",
 shopify_plus="Yes",shopify_plus_evidence="Agency (XgenTech) Shopify Plus build case study",
 operational_signal="Subscription-first with subscribe-and-save on every PDP; subscription platform transitions; wholesale page; own mobile app; reported 100% DTC, bootstrapped $50M-$100M",
 automation_opportunity="Potential opportunity: automating subscription lifecycle and wholesale inquiry handling alongside a high-volume DTC store",
 buying_intent="High",personalization_detail="Subscription-first DTC brand with subscribe-and-save on every product page and a native mobile app",
 personalization_reason="Subscription volume and app + web channels drive recurring operational workload",
 source_urls=["https://xgentech.net/blogs/our-work/transparent-labs","https://www.shopify.com/partners/directory/partner/xgentech","https://www.transparentlabs.com/pages/wholesale","https://www.transparentlabs.com/pages/contact-us","https://apps.apple.com/us/app/transparent-labs/id6450960870","https://www.elliott.org/company-contacts/transparent-labs-customer-service-contacts/"],
 evidence_type="Agency Plus case study; Shopify Partner directory",research_confidence="High",notes="Founder name conflicting in results (summary named Trevor Hiltbrand; ContactOut lists Edward Ionescu) - left blank. HQ 7 S 1550 W, Lindon UT."),
R(company="Four Sigmatic",website="https://us.foursigmatic.com",shopify_store_url="https://us.foursigmatic.com",state="California",city="Santa Monica",industry="Functional food & beverage",product_category="Mushroom coffee, adaptogen blends, protein",
 prospect_name="Tero Isokauppila",first_name="Tero",job_title="Founder & CEO",contact_source_url="https://www.zoominfo.com/p/Tero-Isokauppila/1921500113",
 shopify_verified="Yes",shopify_evidence="AbsoluteWeb case study: migrated from headless to Shopify native frontend; Anatta 6-year Shopify partnership",shopify_evidence_url="https://absoluteweb.com/case-study/four-sigmatic/",
 shopify_plus_evidence="Agency case studies reference Shopify; Plus not explicitly confirmed in results seen",
 shopify_apps="Rebuy (smart cart); Klaviyo-style email flows via Class A Media; UpScribe",operational_signal="50% subscribe & save model; ships to 100+ countries; 28 back-end apps integrated (Anatta); Whole Foods retail; membership program",
 automation_opportunity="Potential opportunity: streamlining international order handling and the 28-app back-end stack with automated workflows",
 buying_intent="Medium",personalization_detail="Integrated 28 back-end applications, ran 240+ CRO tests and ships to 100+ countries",
 personalization_reason="A large app stack and international shipping multiply data sync points",
 source_urls=["https://absoluteweb.com/case-study/four-sigmatic/","https://anatta.io/case-study/foursigmatic","https://www.classamedia.com/case-studies/four-sigmatic","https://www.postpilot.com/case-studies/four-sigmatic","https://www.skailama.com/blog/top-25-healthcare-brands-using-shopify","https://www.zoominfo.com/p/Tero-Isokauppila/1921500113","https://us.foursigmatic.com/pages/partners-and-press"],
 evidence_type="Agency case studies; App vendor case study",research_confidence="High",notes="Finnish-founded; US office in Santa Monica per search summary."),
R(company="Laird Superfood",website="https://lairdsuperfood.com",shopify_store_url="https://lairdsuperfood.com",industry="Food & beverage",product_category="Coffee creamers, superfood coffee, plant-based foods",
 prospect_name="Jason Vieth",first_name="Jason",job_title="CEO",contact_source_url="https://investors.lairdsuperfood.com/governance/executive-management/default.aspx",
 shopify_verified="Yes",shopify_evidence="Official Shopify case study: wholesale channel now sells more than consumer business",shopify_evidence_url="https://www.shopify.com/case-studies/laird-superfood",
 shopify_plus="Yes",shopify_plus_evidence="Shopify Plus blog: migrated to Shopify in 2016 and upgraded to Plus; Plus wholesale channel increased sales 550%",
 product_count_signal="Multi-product catalog (/collections/all)",operational_signal="Password-protected wholesale portal with custom pricing; retail at Walmart and Target; store locator; Nasdaq-listed; new CFO Sept 2026",
 automation_opportunity="Potential opportunity: extending wholesale portal automation to retail replenishment and DTC subscription reporting",
 buying_intent="High",personalization_detail="Runs a password-protected Shopify wholesale portal with negotiated pricing; wholesale revenue surpassed DTC",
 personalization_reason="B2B plus DTC plus mass retail creates pricing, order and inventory workflows ripe for automation",
 source_urls=["https://www.shopify.com/case-studies/laird-superfood","https://www.shopify.com/enterprise/blog/how-laird-superfood-is-using-the-shopify-plus-wholesale-channel-to-increase-sales-550","https://lairdsuperfood.com/collections/all","https://lairdsuperfood.com/pages/store-locator","https://www.target.com/b/laird-superfood/-/N-q643lewog74","https://investors.lairdsuperfood.com/governance/executive-management/default.aspx","https://bizwest.com/2026/09/14/johnson-named-finance-chief-at-laird-superfood/"],
 evidence_type="Shopify Plus case study; Investor relations; Press",research_confidence="High",notes="Public company (active, CFO appointed Sept 2026)."),
R(company="Fly By Jing",website="https://flybyjing.com",shopify_store_url="https://flybyjing.com",state="California",city="Los Angeles",industry="Food",product_category="Chili crisp, sauces, pantry",
 prospect_name="Jing Gao",first_name="Jing",job_title="Founder",contact_source_url="https://www.shopify.com/blog/fly-by-jing-recipe-for-success",
 email="hello@flybyjing.com",email_source_url="https://flybyjing.com/pages/contact",email_note="Also wholesale@flybyjing.com and support@flybyjing.com surfaced in same search",
 shopify_verified="Yes",shopify_evidence="Multiple Shopify blog features; StoreInspect Shopify analysis",shopify_evidence_url="https://storeinspect.com/shopify-store/fly-by-jing",
 shopify_apps="Klaviyo, Gorgias (per search summary)",operational_signal="Retail in Target, Walmart, Whole Foods; wholesale via Faire and wholesale inbox; store locator; eight-figure brand per Shopify",
 automation_opportunity="Potential opportunity: automating wholesale/Faire order intake alongside DTC and retail replenishment",
 buying_intent="Medium",personalization_detail="Runs wholesale via Faire and a dedicated wholesale inbox while selling in Target, Walmart and Whole Foods",
 personalization_reason="Mixing wholesale marketplaces, retail and DTC creates manual reconciliation work",
 source_urls=["https://www.shopify.com/blog/fly-by-jing-recipe-for-success","https://www.shopify.com/blog/aapi-heritage-month-fly-by-jing","https://storeinspect.com/shopify-store/fly-by-jing","https://flybyjing.com/pages/contact","https://www.faire.com/brand/b_6v0qhuk6mq","https://flybyjing.com/pages/store-locator"],
 evidence_type="Shopify blog; Tech profile",research_confidence="High",notes="Mailing address PMB in Los Angeles per contact summary."),
R(company="Kettle & Fire",website="https://www.kettleandfire.com",shopify_store_url="https://kettleandfire-dev.myshopify.com",state="Texas",city="Austin",industry="Food",product_category="Bone broth, soups",
 prospect_name="Justin Mares",first_name="Justin",job_title="Co-founder",contact_source_url="https://theorg.com/org/kettle-fire/org-chart/justin-mares",
 shopify_verified="Yes",shopify_evidence="kettleandfire-dev.myshopify.com page appears in search results; storefront uses /products/ and /collections/ paths",shopify_evidence_url="https://kettleandfire-dev.myshopify.com/pages/about-us",
 product_count_signal="Multiple broth and bundle collections (filters=bundle, broths)",operational_signal="Bundles; retail at Target and Walmart; Amazon store",
 automation_opportunity="Potential opportunity: automating bundle inventory and retail/Amazon/DTC channel sync",
 buying_intent="Low",personalization_detail="Sells bundles on its Shopify store while stocked at Target, Walmart and on Amazon",
 personalization_reason="Multichannel inventory for shelf-stable goods benefits from automated sync",
 source_urls=["https://kettleandfire-dev.myshopify.com/pages/about-us","https://www.kettleandfire.com/collections/products","https://www.kettleandfire.com/a/collections/products?filters=bundle","https://www.target.com/s/kettle+and+fire+bone+broth","https://www.amazon.com/stores/KettleFire/page/10651198-79FC-453B-9B5B-581B313C6A02","https://theorg.com/org/kettle-fire/org-chart/justin-mares","https://www.linkedin.com/in/justinmares/"],
 evidence_type="myshopify domain; Shopify URL patterns; Org chart",research_confidence="Medium",notes="Justin Mares' LinkedIn now shows CEO of Truemed; confirm current Kettle & Fire leadership. Personal email from data broker not used."),
R(company="Graza",website="https://www.graza.co",shopify_store_url="https://www.graza.co",state="New York",city="Brooklyn",industry="Food",product_category="Olive oil",
 prospect_name="Andrew Benin",first_name="Andrew",job_title="Co-founder & CEO",contact_source_url="https://www.linkedin.com/in/andrew-benin-96340225/",
 shopify_verified="Likely",shopify_evidence="Launch story references Graza turning on its Shopify site; Shopify Masters podcast episode; storefront /blogs/ path",shopify_evidence_url="https://medium.com/better-marketing/the-marketing-genius-behind-grazas-sensational-launch-5eb6ac55d35e",
 product_count_signal="Small core line (two hero SKUs: Sizzle and Drizzle)",shopify_apps="Klaviyo (Klaviyo blog)",operational_signal="Sold out first week; strong retail sell-through; influencer gifting program",
 automation_opportunity="Potential opportunity: automating influencer gifting shipments and retail vs DTC inventory allocation",
 buying_intent="Low",personalization_detail="Gifted 25 packs per week to food creators before launch and sold out in its first week",
 personalization_reason="Recurring gifting shipments and demand spikes create repeatable fulfillment tasks",
 source_urls=["https://medium.com/better-marketing/the-marketing-genius-behind-grazas-sensational-launch-5eb6ac55d35e","https://open.spotify.com/episode/2tReRhPwRAo96ml0dWZ8yf","https://www.klaviyo.com/blog/guerrilla-marketing-for-ecommerce","https://www.graza.co/blogs/culture/casual-chats-with-andrew-benin","https://www.linkedin.com/in/andrew-benin-96340225/","https://www.cnbc.com/2024/06/07/how-graza-olive-oil-co-founder-andrew-benin-built-the-business.html"],
 evidence_type="Press; Podcast; App vendor blog",research_confidence="Medium",notes="Limited catalog lowers operational complexity."),
]
p="/tmp/claude-0/-home-user-rappido/671930c5-e8f7-572b-8a98-f01973c2106a/scratchpad/batch1/seg3_us_health_food.json"
json.dump(recs,open(p,"w"),indent=1,ensure_ascii=False)
print(len(recs))
