import json
NOEMAIL="No verified email"
STATUS=" No closure/administration signals seen in search results; dedicated status search not run (session search budget exhausted)."
def R(**k):
    base=dict(company="",website="",shopify_store_url="",country="United Kingdom",state="",city="",industry="",product_category="",company_size="Not verified",
      prospect_name="",first_name="",job_title="",contact_source_url="",email="",email_source_url="",email_note=NOEMAIL,
      shopify_verified="",shopify_evidence="",shopify_evidence_url="",shopify_plus="Not verified",shopify_plus_evidence="",
      product_count_signal="Not verified",shopify_apps="Not verified",operational_signal="",automation_opportunity="",buying_intent="Medium",
      personalization_detail="",personalization_reason="",source_urls=[],evidence_type="",research_confidence="Medium",notes="")
    base.update(k); base["notes"]=(base["notes"]+STATUS).strip(); return base
recs=[
R(company="Missoma",website="https://www.missoma.com",shopify_store_url="https://www.missoma.com",city="",industry="Jewellery",product_category="Demi-fine jewellery",
 shopify_verified="Yes",shopify_evidence="Shopify case study and Shopify Plus customer page: Missoma replatformed to Shopify Plus in eight days before Christmas",shopify_evidence_url="https://www.shopify.com/au/case-studies/missoma",
 shopify_plus="Yes",shopify_plus_evidence="Shopify Plus customer page (shopify.com/my/plus/customers/missoma) describes migration of its $25M business to Shopify Plus",
 operational_signal="$25M business migrated in 8 days during peak month; stocked in Selfridges, Harvey Nichols and Nordstrom (wholesale); 97% of sales DTC; replatform driven by international capacity planning",
 automation_opportunity="Potential opportunity: automating wholesale/retail-partner order and stock sync alongside high-volume DTC peak trading.",
 buying_intent="High",personalization_detail="Stocked in Selfridges, Harvey Nichols and Nordstrom while 97% of sales remain direct to customer",
 personalization_reason="Running wholesale accounts beside a dominant DTC channel creates inventory allocation and order-routing workload that automation can reduce.",
 source_urls=["https://www.shopify.com/au/case-studies/missoma","https://www.shopify.com/my/plus/customers/missoma","https://www.wemakewebsites.com/blog/missoma-layering-lab"],
 evidence_type="Shopify case study; Shopify Plus customer page; Agency blog",research_confidence="High",notes="HQ city not evidenced in results."),
R(company="Finisterre",website="https://finisterre.com",shopify_store_url="https://finisterre.com",industry="Outdoor apparel",product_category="Outdoor clothing and surf apparel",
 shopify_verified="Yes",shopify_evidence="Shopify case study: Finisterre opened 11 physical stores and launched a US regional site on Shopify",shopify_evidence_url="https://www.shopify.com/case-studies/finisterre",
 shopify_apps="Ometria (named in Shopify case study)",
 operational_signal="11 new physical store openings; US regional website launched with plans for two more; ~30% of revenue from in-store sales; online/offline data integration needs",
 automation_opportunity="Potential opportunity: automating omnichannel data flows between store sales, online orders and CRM (Ometria) across regional sites.",
 buying_intent="Medium",personalization_detail="Around 30% of revenue comes from its physical stores, with 11 new stores opened and a US regional site launched on Shopify",
 personalization_reason="Blending retail and online data across regions increases reconciliation and customer-data sync work.",
 source_urls=["https://www.shopify.com/case-studies/finisterre","https://en.wikipedia.org/wiki/Finisterre_(retailer)","https://www.simplyshop.app/blog/ecommerce-case-study-of-finisterre-shopify-themes-bestsellers-and-competitor-insights/"],
 evidence_type="Shopify case study",research_confidence="High",notes="Plus tier not explicitly stated in snippet seen."),
R(company="Jaded London",website="https://jadedldn.com",shopify_store_url="https://jadedldn.com",city="London",state="England",industry="Fashion",product_category="Womenswear and menswear fashion",
 shopify_verified="Yes",shopify_evidence="Shopify case study: Jaded London manages 7 international markets with a lean ecommerce team on Shopify (seven years on Shopify)",shopify_evidence_url="https://www.shopify.com/case-studies/jaded-london",
 shopify_apps="Shopify Sidekick; Shopify Translate & Adapt (custom workflow via API)",
 operational_signal="7 international markets; custom translation workflow synced with Translate & Adapt API; head of ecommerce previously fielded 10+ analytics requests per week; saved 10-15 hours/week with AI",
 automation_opportunity="Potential opportunity: extending automation from analytics/translation into cross-market merchandising, pricing and ops workflows.",
 buying_intent="High",personalization_detail="Runs 7 international markets with a custom translation workflow synced to Shopify's Translate & Adapt API",
 personalization_reason="A lean team already investing in automation across seven markets is a strong fit for further workflow automation.",
 source_urls=["https://www.shopify.com/case-studies/jaded-london","https://ecomscout.com/stores/jadedldn.com"],
 evidence_type="Shopify case study; Store analysis profile",research_confidence="High",notes="City 'London' taken from brand name only; HQ address not separately verified."),
R(company="BrainGain",website="https://braingain.fit",shopify_store_url="https://braingain.fit",industry="Fitness",product_category="Space-saving home gym equipment",
 shopify_verified="Yes",shopify_evidence="Featured on Shopify UK case studies: grew to 100,000+ customers across 30+ countries and upgraded to Shopify Plus",shopify_evidence_url="https://www.shopify.com/uk/case-studies",
 shopify_plus="Yes",shopify_plus_evidence="Shopify UK case study states BrainGain upgraded to Shopify Plus; first-year GMV +45%, orders +35%, AOV +7.7%",
 operational_signal="100,000+ customers; ships to 30+ countries; cross-border demand; GMV +45% and orders +35% in first year on Plus",
 automation_opportunity="Potential opportunity: automating cross-border fulfilment, duties/shipping exceptions and bulky-item order routing.",
 buying_intent="Medium",personalization_detail="Sells to 100,000+ customers across 30+ countries after upgrading to Shopify Plus for cross-border demand",
 personalization_reason="Rising cross-border order volume for bulky equipment increases shipping and support workload.",
 source_urls=["https://www.shopify.com/uk/case-studies","https://www.trustpilot.com/review/braingain.fit"],
 evidence_type="Shopify case study listing",research_confidence="Medium",notes="UK fitness brand per Shopify UK case study summary; website domain taken from Trustpilot URL."),
R(company="Oh Polly",website="https://www.ohpolly.com",shopify_store_url="https://www.ohpolly.com",industry="Fashion",product_category="Womenswear / occasionwear",
 prospect_name="Claire Henderson",first_name="Claire",job_title="Co-founder",contact_source_url="https://resources.algolia.com/customer-stories/casestudy-ohpolly",
 shopify_verified="Yes",shopify_evidence="Agency (By Association Only) Shopify Plus case study: migration from Magento to Shopify Plus",shopify_evidence_url="https://www.byassociationonly.com/case-studies/oh-polly",
 shopify_plus="Yes",shopify_plus_evidence="By Association Only Shopify Plus case study; Algolia customer story names Shopify Plus",
 shopify_apps="Algolia; LoyaltyLion; Tapcart",
 operational_signal="Offices in Glasgow, Liverpool, Los Angeles, Dhaka and Guangzhou; Shopify Markets multi-currency; four websites; expansion stores for key markets; high-volume drops",
 automation_opportunity="Potential opportunity: automating drop-launch operations and multi-store catalogue/stock sync across its four sites.",
 buying_intent="High",personalization_detail="Operates four storefronts with offices in Glasgow, Liverpool, Los Angeles, Dhaka and Guangzhou",
 personalization_reason="Multiple stores plus sourcing offices abroad create multi-store sync and supply-chain coordination work.",
 source_urls=["https://www.byassociationonly.com/case-studies/oh-polly","https://www.algolia.com/customers/Oh-Polly","https://resources.algolia.com/customer-stories/casestudy-ohpolly","https://loyaltylion.com/customers/oh-polly","https://www.tapcart.com/case-studies/oh-polly"],
 evidence_type="Agency Shopify Plus case study; App vendor case studies",research_confidence="High",notes="Founded 2015 by Claire Henderson and Mike Branney."),
R(company="Lounge Underwear",website="https://lounge.com",shopify_store_url="https://lounge.com",industry="Fashion",product_category="Underwear, loungewear and swimwear",company_size="~120 staff (Shopify Plus case study)",
 shopify_verified="Yes",shopify_evidence="Shopify Plus customer case study: scales to 25 orders per second",shopify_evidence_url="https://www.shopify.com/ng/plus/customers/lounge-underwear",
 shopify_plus="Yes",shopify_plus_evidence="Shopify Plus customer page; agency Made by Field Shopify Plus case study",
 operational_signal="$70M revenue; 120 staff; eight stores (US, Australia, multiple EU markets); 1,000+ orders per minute at BFCM peak; £1m sales in an hour",
 automation_opportunity="Potential opportunity: automating peak-event order handling, fraud/exception triage and multi-store inventory sync.",
 buying_intent="High",personalization_detail="Handled 25 orders per second at BFCM peak across eight international Shopify Plus stores",
 personalization_reason="Extreme peak volumes across eight stores magnify manual fulfilment and support tasks.",
 source_urls=["https://www.shopify.com/ng/plus/customers/lounge-underwear","https://www.shopify.com/hk-en/case-studies/lounge-underwear","https://madebyfield.co.uk/projects/lounge-underwear"],
 evidence_type="Shopify Plus case study; Agency case study",research_confidence="High",notes="Website domain assumed from brand; not shown in snippets - verify."),
R(company="Represent",website="https://uk.representclo.com",shopify_store_url="https://uk.representclo.com",city="Manchester",state="England",industry="Fashion",product_category="Luxury streetwear",
 prospect_name="George Heaton",first_name="George",job_title="Co-founder",contact_source_url="https://www.shopify.com/enterprise/blog/founder-story-represent",
 shopify_verified="Yes",shopify_evidence="Shopify case study: Represent on track to reach £100M revenue while partnering with Shopify",shopify_evidence_url="https://www.shopify.com/case-studies/represent",
 shopify_plus="Yes",shopify_plus_evidence="Shopify case study describes Represent as one of the fastest-growing stores on Shopify Plus; Superco (Shopify Premier Partner) case",
 operational_signal="Flagship stores in London, Manchester and Los Angeles; wholesale with Selfridges, Harrods, Harvey Nichols; ~£100M revenue; mainline, womenswear and 247 performance lines",
 automation_opportunity="Potential opportunity: automating wholesale, retail and DTC inventory allocation across UK/US stores.",
 buying_intent="High",personalization_detail="Runs flagship stores in London, Manchester and LA plus wholesale with Selfridges, Harrods and Harvey Nichols",
 personalization_reason="Retail, wholesale and global DTC channels at ~£100M scale increase cross-channel ops complexity.",
 source_urls=["https://www.shopify.com/case-studies/represent","https://www.shopify.com/enterprise/blog/founder-story-represent","https://superco.io/pages/represent","https://uk.representclo.com/pages/about","https://en.wikipedia.org/wiki/Represent_(clothing_brand)"],
 evidence_type="Shopify case study; Shopify founder story; Agency case study",research_confidence="High",notes="Founded 2011 by brothers George and Mike Heaton in Manchester."),
R(company="Wild",website="https://wearewild.com",shopify_store_url="https://wearewild.com",industry="Beauty / personal care",product_category="Refillable deodorant, body wash, lip balm",
 prospect_name="Charlie Bowes-Lyon",first_name="Charlie",job_title="Co-founder",contact_source_url="https://getrecharge.com/case-studies/wild-deodorant/",
 shopify_verified="Yes",shopify_evidence="Recharge case study and Eastside Co custom Shopify build for Wild",shopify_evidence_url="https://eastsideco.com/portfolio/wild-deo",
 shopify_apps="Recharge",
 operational_signal="6-digit subscriber count in 7 months; refill subscription model; US storefront (/us/); help centre at support.wearewild.com",
 automation_opportunity="Potential opportunity: automating subscription lifecycle tasks (skips, swaps, failed payments) and refill-related support tickets.",
 buying_intent="High",personalization_detail="Built a six-figure subscriber base within 7 months on a refill subscription powered by Recharge",
 personalization_reason="High subscriber volume generates recurring billing, change and support requests suited to automation.",
 source_urls=["https://getrecharge.com/case-studies/wild-deodorant/","https://eastsideco.com/portfolio/wild-deo","https://wearewild.com/us/pages/usa-subscription-landing-page","https://support.wearewild.com/hc/en-gb/articles/360021593359-How-does-the-subscription-work"],
 evidence_type="App vendor case study; Agency case study",research_confidence="High",notes=""),
R(company="Grind",website="https://grind.co.uk",shopify_store_url="https://grind.co.uk",city="London",state="England",industry="Food and drink",product_category="Coffee, compostable pods, cafes",
 shopify_verified="Yes",shopify_evidence="Shopify UK blog: how Grind turned a single cafe into an 8-figure DTC coffee brand; Littledata case study",shopify_evidence_url="https://www.shopify.com/uk/blog/grind-dtc-expansion",
 shopify_apps="Littledata",
 operational_signal="Cafe estate of almost a dozen London locations; subscriptions; stockist network; online revenue scaled 50x in 3 months",
 automation_opportunity="Potential opportunity: automating subscription management and stockist/wholesale order handling alongside DTC.",
 buying_intent="Medium",personalization_detail="Grew from a Shoreditch cafe to an 8-figure DTC brand with coffee-pod subscriptions and a stockist network",
 personalization_reason="Combining cafes, subscriptions and stockists creates multi-channel fulfilment work.",
 source_urls=["https://www.shopify.com/uk/blog/grind-dtc-expansion","https://www.littledata.io/case-studies/grind-case-study","https://grind.co.uk/pages/locations","https://grind.co.uk/pages/stockist"],
 evidence_type="Shopify blog feature; App vendor case study",research_confidence="High",notes=""),
R(company="Astrid & Miyu",website="https://www.astridandmiyu.com",shopify_store_url="https://www.astridandmiyu.com",city="London",state="England",industry="Jewellery",product_category="Contemporary jewellery",
 prospect_name="Connie Nam",first_name="Connie",job_title="Founder",contact_source_url="https://www.byassociationonly.com/case-studies/astrid-and-miyu",
 shopify_verified="Yes",shopify_evidence="Shopify UK case study on Astrid & Miyu using Shopify POS; 1M+ orders processed through Shopify",shopify_evidence_url="https://www.shopify.com/uk/case-studies/astrid-and-miyu-pos",
 shopify_plus="Yes",shopify_plus_evidence="By Association Only Shopify Plus case study; We Make Websites replatform to Shopify Plus",
 shopify_apps="Shopify POS",
 operational_signal="23 brick-and-mortar stores across UK, EU and US on Shopify POS; 1M+ orders online and offline; engraving and build-your-own set personalisation",
 automation_opportunity="Potential opportunity: automating personalised/engraved order routing and store-to-online stock transfers.",
 buying_intent="High",personalization_detail="Runs 23 stores across the UK, EU and US on Shopify POS and has processed over a million orders",
 personalization_reason="Unified retail and online at this scale, plus engraving personalisation, creates operational hand-offs worth automating.",
 source_urls=["https://www.shopify.com/uk/case-studies/astrid-and-miyu-pos","https://www.byassociationonly.com/case-studies/astrid-and-miyu","https://www.facebook.com/wemakewebsites/videos/we-recently-launched-astrid-miyu-shiny-new-store-the-london-based-contemporary-j/344590179505667/","https://www.zoominfo.com/c/astrid-miyu-ltd/357004409"],
 evidence_type="Shopify case study; Agency Shopify Plus case study",research_confidence="High",notes="Website domain assumed from brand; not shown in snippets - verify."),
R(company="RIXO",website="https://rixolondon.com",shopify_store_url="https://rixolondon.com",city="London",state="England",industry="Fashion",product_category="Premium womenswear",
 prospect_name="Henrietta Rix",first_name="Henrietta",job_title="Co-founder",contact_source_url="https://blubolt.com/case-study/rixo/",
 shopify_verified="Yes",shopify_evidence="blubolt Shopify Plus Online Store 2.0 case study; Drapers webinar with Rixo and Shopify Plus",shopify_evidence_url="https://blubolt.com/case-study/rixo/",
 shopify_plus="Yes",shopify_plus_evidence="blubolt agency Shopify Plus case study (19% conversion uplift, 26% revenue boost)",
 shopify_apps="Harper Concierge (Try Before You Buy integration)",
 operational_signal="Physical stores (stores page); US localized storefront (/en-us/); extended sizing capsule 12-26; locked collections for loyal customers; clicks-and-bricks model",
 automation_opportunity="Potential opportunity: automating try-before-you-buy returns handling and store/online inventory coordination.",
 buying_intent="Medium",personalization_detail="Offers Try Before You Buy via Harper Concierge in London and locked collections for loyal customers",
 personalization_reason="Try-before-you-buy and gated collections add return and customer-segmentation workflows.",
 source_urls=["https://blubolt.com/case-study/rixo/","https://www.drapersonline.com/insight/drapers-connects/video-making-the-most-of-clicks-and-bricks-with-rixo-and-shopify-plus","https://rixolondon.com/en-us/pages/stores","https://rixolondon.com/en-us/collections/extended-sizing-capsule"],
 evidence_type="Agency Shopify Plus case study; Trade press",research_confidence="High",notes="Founded 2015 by Henrietta Rix and Orlagh McCloskey. City inferred from brand name 'RIXO London'."),
R(company="Pooch & Mutt",website="https://poochandmutt.com",shopify_store_url="https://poochandmutt.com",state="England",city="",industry="Pet",product_category="Dog food and supplements",
 shopify_verified="Yes",shopify_evidence="Underwaterpistol case study on Pooch & Mutt's Shopify store and dog food subscription",shopify_evidence_url="https://www.underwaterpistol.com/work/pooch-and-mutt",
 shopify_apps="Recharge; LoyaltyLion; Klaviyo (per D2Cville tech stack)",
 operational_signal="Dog food subscription service; conversion +45% and sales +119% after optimisation; founded 2007",
 automation_opportunity="Potential opportunity: automating subscription churn-prevention and replenishment reminders.",
 buying_intent="Medium",personalization_detail="Runs a dog-food subscription on Shopify with Recharge, LoyaltyLion and Klaviyo",
 personalization_reason="Subscription churn and loyalty flows benefit from automated retention workflows.",
 source_urls=["https://www.underwaterpistol.com/work/pooch-and-mutt","https://www.d2cville.com/brands/pooch--mutt","https://swankyagency.com/pet-shopify-stores/"],
 evidence_type="Agency case study; Tech stack profile",research_confidence="Medium",notes="Based in Northamptonshire, England per search summary."),
R(company="Absolute Collagen",website="https://www.absolutecollagen.com",shopify_store_url="https://www.absolutecollagen.com",industry="Supplements",product_category="Liquid marine collagen supplements",
 shopify_verified="Yes",shopify_evidence="Eastside Co Shopify Plus website build; shop.app merchant page",shopify_evidence_url="https://eastsideco.com/portfolio/absolute-collagen",
 shopify_plus="Yes",shopify_plus_evidence="Eastside Co portfolio: Shopify Plus store design and build",
 shopify_apps="Recharge; Gorgias; Relo; Aircall (Gorgias integration)",
 operational_signal="Subscription service with Recharge customer portal; Gorgias support with Aircall; Relo reorder prediction (+16% new subscribers)",
 automation_opportunity="Potential opportunity: automating subscription support tickets and reorder/cross-sell triggers.",
 buying_intent="Medium",personalization_detail="Uses Recharge subscriptions with Gorgias and Relo to drive a 16% uplift in new subscribers",
 personalization_reason="An already tool-heavy subscription stack indicates appetite for further workflow automation.",
 source_urls=["https://eastsideco.com/portfolio/absolute-collagen","https://www.reloapp.co/case-studies/how-absolute-collagen-increased-new-subscribers-by-16-with-relo","https://www.gorgias.com/customers/absolute-collagen","https://www.absolutecollagen.com/pages/privacy-policy","https://shop.app/m/absolutecollagen"],
 evidence_type="Agency Shopify Plus case study; App vendor case studies",research_confidence="High",notes="A the-absolute-collagen.myshopify.com result appeared but was not clearly tied to this brand, so not used."),
R(company="Huel",website="https://huel.com",shopify_store_url="https://huel.com",industry="Food and drink / nutrition",product_category="Nutritionally complete meals, powders, RTD drinks, bars",company_size="120 employees (Shopify case study)",
 shopify_verified="Yes",shopify_evidence="Shopify case study: Huel onboards staff 9x faster with new Shopify Plus Admin",shopify_evidence_url="https://www.shopify.com/case-studies/huel",
 shopify_plus="Yes",shopify_plus_evidence="Shopify Plus customer page and case study",
 operational_signal="Nine stores around the globe; subscription model; £140m revenue in 2022; large volume of backend tasks",
 automation_opportunity="Potential opportunity: automating cross-store ops and subscription-change handling across nine storefronts.",
 buying_intent="High",personalization_detail="Operates nine Shopify Plus stores globally with a flexible subscription model",
 personalization_reason="Multi-store global subscriptions create heavy backend workloads the case study itself highlights.",
 source_urls=["https://www.shopify.com/case-studies/huel","https://www.shopify.com/ph/plus/customers/huel","https://swankyagency.com/portfolio/huel/"],
 evidence_type="Shopify Plus case study; Agency portfolio",research_confidence="High",notes="Website domain assumed from brand; not shown in snippets - verify."),
R(company="Omorovicza",website="https://www.omorovicza.com",shopify_store_url="https://www.omorovicza.com",country="",industry="Beauty / skincare",product_category="Luxury skincare",
 shopify_verified="Yes",shopify_evidence="By Association Only Shopify Plus case study: migration to Shopify 2.0",shopify_evidence_url="https://www.byassociationonly.com/case-studies/omorovicza",
 shopify_plus="Yes",shopify_plus_evidence="Agency case study titled 'Shopify Plus Case Study - Omorovicza'",
 operational_signal="Online treatment booking; custom bundle builder and checkout upsell; institutes in Budapest and London (Harrods, Liberty, Mayfair)",
 automation_opportunity="Potential opportunity: automating treatment-booking to product-order follow-ups and bundle fulfilment.",
 buying_intent="Low",personalization_detail="Enables online treatment bookings for its institutes in Budapest and London (Harrods, Liberty, Mayfair)",
 personalization_reason="Combining services bookings with product ecommerce adds scheduling and fulfilment hand-offs.",
 source_urls=["https://www.byassociationonly.com/case-studies/omorovicza","https://www.linkedin.com/posts/by-association-only_shopify-plus-case-study-omorovicza-l-by-activity-7300133389725032448-rdEF"],
 evidence_type="Agency Shopify Plus case study",research_confidence="Medium",notes="HQ country not evidenced (Budapest and London locations); segment fit to UK should be checked in QA. Website domain assumed."),
R(company="LYMA",website="https://lyma.life",shopify_store_url="https://lyma.life",country="",industry="Wellness / supplements",product_category="Supplements and beauty tech",
 shopify_verified="Yes",shopify_evidence="Underwaterpistol Shopify Plus case study: migration from custom platform to Shopify Plus",shopify_evidence_url="https://www.underwaterpistol.com/work/lyma",
 shopify_plus="Yes",shopify_plus_evidence="Underwaterpistol agency Shopify Plus case study",
 shopify_apps="Patchworks (iPaaS) integration with Bleckmann 3PL",
 operational_signal="Demand in UK and US with plans for Europe, Middle East and East Asia; Shopify Plus-Bleckmann real-time sync via Patchworks; membership card loyalty",
 automation_opportunity="Potential opportunity: extending automated workflows beyond 3PL sync into international expansion ops and membership management.",
 buying_intent="Medium",personalization_detail="Connects Shopify Plus to Bleckmann logistics via Patchworks for real-time data sync",
 personalization_reason="Existing investment in integration automation signals openness to further ops automation.",
 source_urls=["https://www.underwaterpistol.com/work/lyma","https://www.wearepatchworks.com/blogs/news/lyma-boosts-operational-efficiency-with-the-patchworks-ipaas-platform"],
 evidence_type="Agency Shopify Plus case study; Integration vendor case study",research_confidence="Medium",notes="HQ country not explicitly evidenced (UK demand cited). Website domain assumed - verify."),
R(company="Pip & Nut",website="https://pipandnut.com",shopify_store_url="https://pipandnut.com",city="London",state="England",industry="Food and drink",product_category="Nut butters and snacks",
 shopify_verified="Yes",shopify_evidence="Superrb agency case study: new Pip & Nut Shopify eCommerce website",shopify_evidence_url="https://www.superrb.com/our-work/pip-nut",
 operational_signal="Stocked in 6,000+ stores worldwide; B Corp; subscribe-and-save toggle; bundle offers",
 automation_opportunity="Potential opportunity: automating subscription and bundle fulfilment alongside its large retail distribution.",
 buying_intent="Medium",personalization_detail="Started at London's Maltby Street Market in 2013 and now sold in over 6,000 stores worldwide, with subscribe-and-save online",
 personalization_reason="Balancing large retail distribution with DTC subscriptions creates planning and fulfilment work.",
 source_urls=["https://www.superrb.com/our-work/pip-nut","https://dribbble.com/shots/10828201-Pip-Nut-Shopify-Store","https://www.suttoncommerce.co.uk/blog/best-nut-butter-shopify-stores","https://www.cooperparry.com/news/how-i-built-the-uks-fastest-growing-nut-butter-brand/"],
 evidence_type="Agency case study; Shopify store listings",research_confidence="Medium",notes="City inferred from Maltby Street Market origin; HQ not separately verified. Website domain assumed."),
R(company="Snag",website="https://snagtights.com",shopify_store_url="https://snagtights.com",country="",industry="Fashion",product_category="Size-inclusive tights and clothing",
 shopify_verified="Yes",shopify_evidence="Shop Circle case study: Snag integrated six regional Shopify stores into one mobile app",shopify_evidence_url="https://shopcircle.co/blogs/case-studies/global-reach-simplified-case-study-of-snag-tights",
 product_count_signal="All products available in sizes 4 to 36 (many variants)",
 operational_signal="Six Shopify stores (ANZ, UK, USA, EU English and German, Canada) in different currencies; sizes 4-36 on every product; Amazon presence",
 automation_opportunity="Potential opportunity: automating catalogue and inventory sync across six regional Shopify stores.",
 buying_intent="Medium",personalization_detail="Runs six regional Shopify stores (ANZ, UK, US, EU English/German, Canada) in different currencies",
 personalization_reason="Multi-store, multi-currency operations with extensive size variants multiply catalogue maintenance.",
 source_urls=["https://shopcircle.co/blogs/case-studies/global-reach-simplified-case-study-of-snag-tights","https://snagtights.us/","https://snagtights.com/pages/privacy-policy"],
 evidence_type="App vendor case study; Shopify URL patterns",research_confidence="Medium",notes="HQ not evidenced in results; UK store confirmed; verify UK HQ in QA."),
R(company="TALA",website="https://www.wearetala.com",shopify_store_url="https://www.wearetala.com",industry="Fitness / activewear",product_category="Women's activewear and lifestyle clothing",
 prospect_name="Grace Beverley",first_name="Grace",job_title="Founder",contact_source_url="https://www.simplybusiness.co.uk/knowledge/starting-out/grace-beverley-business-profile/",
 shopify_verified="Likely",shopify_evidence="Storefront uses Shopify URL paths (/collections/, /pages/) with localized /en-us/ market; listed among best activewear Shopify stores",shopify_evidence_url="https://www.suttoncommerce.co.uk/blog/best-activewear-shopify-stores",
 operational_signal="Localized US storefront (/en-us/); raised $5.7M to expand; material-transparency product pages",
 automation_opportunity="Potential opportunity: automating drop-launch operations and international (UK/US) order handling.",
 buying_intent="Medium",personalization_detail="Raised $5.7M to expand and runs a localized US storefront alongside UK",
 personalization_reason="Funded international growth increases fulfilment and support demands.",
 source_urls=["https://www.wearetala.com/","https://www.wearetala.com/en-us/collections/activewear","https://www.wearetala.com/en-us/pages/about-us","https://www.suttoncommerce.co.uk/blog/best-activewear-shopify-stores","https://wwd.com/fashion-news/activewear/grace-beverley-raises-5-7m-to-expand-sustainable-activewear-label-tala-1235058383/","https://www.simplybusiness.co.uk/knowledge/starting-out/grace-beverley-business-profile/"],
 evidence_type="Shopify URL patterns; Shopify store list; Press",research_confidence="Medium",notes="Founded 2019 by Grace Beverley."),
R(company="Monica Vinader",website="https://www.monicavinader.com",shopify_store_url="https://www.monicavinader.com",industry="Jewellery",product_category="Demi-fine jewellery (recycled gold and silver)",
 shopify_verified="Likely",shopify_evidence="Featured in multiple Shopify jewellery store roundups; Constructor Shopify partner listing references the brand",shopify_evidence_url="https://ecomposer.io/blogs/case-studies/shopify-jewelry-stores",
 operational_signal="International customer base; Build a Bracelet personalisation; geo-personalized ranking via Constructor",
 shopify_apps="Constructor (product discovery)",
 automation_opportunity="Potential opportunity: automating personalised build-a-bracelet order routing and international fulfilment.",
 buying_intent="Low",personalization_detail="Offers a 'Build a Bracelet' personalisation feature and uses Constructor geo-personalized ranking",
 personalization_reason="Personalised configurable products add order-processing steps.",
 source_urls=["https://ecomposer.io/blogs/case-studies/shopify-jewelry-stores","https://www.identixweb.com/shopify-jewelry-stores/","https://cyruswebtech.com/blogs/news/best-shopify-jewellery-and-accessory-stores","https://www.shopify.com/partners/directory/partner/constructor-io2","https://en.wikipedia.org/wiki/Monica_Vinader"],
 evidence_type="Shopify store roundups; Partner directory",research_confidence="Low",notes="Storefront URL pattern (/shop/) is not a standard Shopify path; Shopify evidence is indirect only - verify in QA."),
R(company="Formerly Known As Haeckels",website="https://haeckels.co.uk",shopify_store_url="https://haeckels.co.uk",industry="Beauty / skincare",product_category="Natural skincare and fragrance",
 shopify_verified="Likely",shopify_evidence="Agency case-study listing describes Haeckels' migration from WordPress to Shopify",shopify_evidence_url="https://www.byassociationonly.com/case-studies",
 operational_signal="Migrated from WordPress to Shopify with storytelling-led redesign",
 automation_opportunity="Potential opportunity: automating order-to-fulfilment and customer follow-up workflows post-migration.",
 buying_intent="Low",personalization_detail="Recently migrated from WordPress to Shopify with a storytelling-led redesign",
 personalization_reason="Post-migration brands often rebuild operational workflows on the new platform.",
 source_urls=["https://www.byassociationonly.com/case-studies"],
 evidence_type="Agency case study listing",research_confidence="Low",notes="Evidence from a search summary of agency case studies; website domain assumed - verify."),
R(company="Gymshark",website="https://www.gymshark.com",shopify_store_url="https://www.gymshark.com",industry="Fitness apparel",product_category="Activewear",
 shopify_verified="Likely",shopify_evidence="Listed in Shopify brand roundup as built on Shopify Plus to handle high traffic peaks",shopify_evidence_url="https://noughtsandones.com/blogs/news/from-beauty-to-fitness-14-big-brands-powered-by-shopify",
 shopify_plus="Not verified",shopify_plus_evidence="Only a third-party roundup seen, no Shopify Plus case study retrieved in this session",
 operational_signal="Global fitness brand; high traffic volumes during peak periods",
 automation_opportunity="Potential opportunity: automating peak-period order exception handling at global scale.",
 buying_intent="Medium",personalization_detail="Described as scaling from startup to global fitness brand on Shopify Plus to absorb peak-traffic launches",
 personalization_reason="Peak-traffic launches drive spikes in fulfilment and support workload.",
 source_urls=["https://noughtsandones.com/blogs/news/from-beauty-to-fitness-14-big-brands-powered-by-shopify"],
 evidence_type="Shopify brand roundup",research_confidence="Low",notes="Enterprise-scale brand; evidence limited to third-party roundup in this session."),
R(company="Fuller's Brewery",website="https://www.fullers.co.uk",shopify_store_url="https://www.fullers.co.uk",industry="Food and drink",product_category="Beer and brewery merchandise",
 shopify_verified="Yes",shopify_evidence="Superrb agency case study: state-of-the-art Shopify website for Fuller's Brewery",shopify_evidence_url="https://www.superrb.com/journal/launching-one-of-the-uks-oldest-breweries-into-the-future",
 operational_signal="One of the UK's oldest breweries launched on Shopify",
 automation_opportunity="Potential opportunity: automating age-verified alcohol order handling and courier exceptions.",
 buying_intent="Low",personalization_detail="Superrb launched a new Shopify website for one of the UK's oldest breweries",
 personalization_reason="Heritage brewer moving DTC online may need streamlined fulfilment workflows.",
 source_urls=["https://www.superrb.com/journal/launching-one-of-the-uks-oldest-breweries-into-the-future"],
 evidence_type="Agency case study",research_confidence="Low",notes="Ownership/corporate structure not verified; website domain assumed - verify."),
R(company="Rave Coffee",website="https://ravecoffee.co.uk",shopify_store_url="https://ravecoffee.co.uk",industry="Food and drink",product_category="Specialty coffee",
 shopify_verified="Yes",shopify_evidence="blubolt case study: 'Rave Coffee - Shopify Plus build by blubolt'",shopify_evidence_url="https://blubolt.com/case-study/full-of-beans-on-shopify-plus",
 shopify_plus="Yes",shopify_plus_evidence="blubolt agency Shopify Plus build case study",
 operational_signal="Shopify Plus build by agency (details not in snippet)",
 automation_opportunity="Potential opportunity: automating coffee subscription and wholesale order workflows.",
 buying_intent="Medium",personalization_detail="Replatformed onto Shopify Plus with agency blubolt ('Full of beans on Shopify Plus')",
 personalization_reason="A recent Plus build suggests capacity for workflow automation on the new stack.",
 source_urls=["https://blubolt.com/case-study/full-of-beans-on-shopify-plus"],
 evidence_type="Agency Shopify Plus case study",research_confidence="Low",notes="Only title-level evidence seen; UK HQ and domain not evidenced - verify."),
R(company="Heist Studios",website="https://www.heist-studios.com",shopify_store_url="https://www.heist-studios.com",industry="Fashion",product_category="Engineered hosiery and shapewear",
 prospect_name="Toby Darbyshire",first_name="Toby",job_title="Co-founder",contact_source_url="https://www.huptechweb.com/blogs/top-shopify-stores-uk",
 shopify_verified="Likely",shopify_evidence="UK Shopify store roundup describes Heist's move from a legacy stack to Shopify",shopify_evidence_url="https://www.huptechweb.com/blogs/top-shopify-stores-uk",
 operational_signal="Engineered hosiery; founded 2014",
 automation_opportunity="Potential opportunity: automating size/fit-driven returns and exchanges.",
 buying_intent="Low",personalization_detail="Co-founded in 2014 by Toby Darbyshire and Fiona Fairhurst, engineer behind Speedo's Fastskin",
 personalization_reason="Fit-engineered products with many sizes generate exchange workflows.",
 source_urls=["https://www.huptechweb.com/blogs/top-shopify-stores-uk"],
 evidence_type="Shopify store roundup",research_confidence="Low",notes="Source attribution of founder snippet uncertain; trading status not checked - verify in QA. Domain assumed."),
]
for r in recs:
    if r["country"]=="" and "HQ" not in r["notes"]: pass
p="/tmp/claude-0/-home-user-rappido/671930c5-e8f7-572b-8a98-f01973c2106a/scratchpad/batch1/seg5_uk.json"
json.dump(recs,open(p,"w"),indent=1,ensure_ascii=False)
from collections import Counter
print(len(recs),Counter(r["buying_intent"] for r in recs))
