import json
def rec(**k):
    base = {"company":"","website":"","shopify_store_url":"","country":"","state":"","city":"","industry":"","product_category":"","company_size":"Not verified","prospect_name":"","first_name":"","job_title":"","contact_source_url":"","email":"","email_source_url":"","email_note":"No verified email","shopify_verified":"","shopify_evidence":"","shopify_evidence_url":"","shopify_plus":"Not verified","shopify_plus_evidence":"","product_count_signal":"Not verified","shopify_apps":"Not verified","operational_signal":"","automation_opportunity":"","buying_intent":"","personalization_detail":"","personalization_reason":"","source_urls":[],"evidence_type":"","research_confidence":"","notes":""}
    base.update(k); return base
R = [
rec(company="Tilley", website="https://www.tilley.com", shopify_store_url="https://www.tilley.com",
 country="Canada", state="Ontario", city="Toronto",
 industry="Apparel & Accessories", product_category="Outdoor/travel hats, apparel and accessories",
 email="tilley@tilley.com", email_source_url="https://www.tilley.com/pages/contact",
 email_note="Generic inbox surfaced in search summary of Tilley contact/FAQ/accessibility pages",
 shopify_verified="Yes", shopify_evidence="Shopify case study: Tilley conversions up 200%, monthly revenue up 120%+ after move to Shopify Plus",
 shopify_evidence_url="https://www.shopify.com/case-studies/tilley",
 shopify_plus="Yes", shopify_plus_evidence="Shopify Plus customer page and JC+CO (Shopify Plus partner) case study describing migration from Adobe Commerce/Magento to Shopify Plus",
 shopify_apps="Klaviyo; Okendo; Gorgias (per Shopify/JC+CO case study)",
 operational_signal="Shifted from wholesale-driven model to digital-first; migrated from Adobe Commerce to Shopify Plus; expanded into Australian market; opened Amazon channel; separate US and UK storefronts",
 automation_opportunity="Potential opportunity: synchronizing inventory and order flows across Shopify storefronts (CA/US/UK/AU), Amazon and wholesale accounts.",
 buying_intent="Medium",
 personalization_detail="Nearly quadrupled ecommerce revenue after moving from Adobe Commerce to Shopify Plus and launching into Australia and Amazon",
 personalization_reason="Multi-market, multi-channel growth on top of a legacy wholesale business increases order routing and inventory sync workload",
 source_urls=["https://www.shopify.com/case-studies/tilley","https://jcand.co/tilley","https://www.shopify.com/ca/plus/customers/tilley","https://www.tilley.com/pages/contact","https://www.tilley.com/pages/accessibility","https://www.tilley.com/uk_en/contact/"],
 evidence_type="Shopify case study; Shopify Plus customer page; Agency case study; Brand contact page",
 research_confidence="High",
 notes="HQ from accessibility page mailing address (60 Gervais Drive, Toronto, ON). No named contact searched due to search budget."),
rec(company="Kit and Ace", website="https://www.kitandace.com", shopify_store_url="https://www.kitandace.com",
 country="Canada", state="British Columbia", city="Vancouver",
 industry="Apparel", product_category="Technical cashmere apparel",
 prospect_name="David Lui", first_name="David", job_title="CEO (Kit and Ace); Co-founder, Unity Brands",
 contact_source_url="https://retail-insider.com/retail-insider/2024/02/anatomy-of-a-leader-david-lui/",
 shopify_verified="Yes", shopify_evidence="Avex Designs case study on re-platforming Kit and Ace from Salesforce Commerce Cloud to Shopify Plus; storefront uses /products/ and /pages/ paths",
 shopify_evidence_url="https://www.avexdesigns.com/work/kit-and-ace/",
 shopify_plus="Yes", shopify_plus_evidence="Avex Designs (agency) Shopify Plus migration case study; iamota case study",
 shopify_apps="Shopify Markets; Shopify POS Go (per Avex and Ecommerce Fastlane)",
 operational_signal="Re-platformed from Salesforce Commerce Cloud; multi-currency/multi-market storefront via Shopify Markets; retail stores using Shopify POS Go; in-store availability shown online; acquired by Unity Brands in July 2023",
 automation_opportunity="Potential opportunity: automating store-to-online inventory visibility and cross-market order routing between retail floors and Shopify Markets storefronts.",
 buying_intent="High",
 personalization_detail="Uses Shopify POS Go on the sales floor and shows in-store availability on product pages after leaving Salesforce Commerce Cloud",
 personalization_reason="Unified retail plus online inventory creates ongoing sync, BOPIS and exception-handling work suited to automation",
 source_urls=["https://www.avexdesigns.com/work/kit-and-ace/","https://ecommercefastlane.com/kit-and-ace-gets-reliable-payment-processing-on-the-sales-floor-with-shopify-pos-go/","https://www.iamota.com/work/kit-ace","https://www.kitandace.com/en-us","https://retail-insider.com/retail-insider/2024/02/anatomy-of-a-leader-david-lui/","https://www.biv.com/news/retail-manufacturing/vancouver-fashion-chain-kit-and-ace-enjoys-renaissance-under-unity-brands-9551779","https://www.newswire.ca/news-releases/unity-brands-inc-acquires-kit-and-ace-technical-apparel-inc--866570897.html"],
 evidence_type="Agency case study; Press article; Brand storefront",
 research_confidence="High",
 notes="HQ Vancouver per Retail Insider/BIV. BIV reports a renaissance under Unity Brands (not distressed)."),
rec(company="Kotn", website="https://kotn.com", shopify_store_url="https://kotn.com",
 country="Canada", state="Ontario", city="Toronto",
 industry="Apparel", product_category="Sustainable cotton basics and home goods",
 company_size="150+ employees (press, 2025)",
 prospect_name="Rami Helali", first_name="Rami", job_title="Co-founder & CEO",
 contact_source_url="https://ca.linkedin.com/in/rami-helali-18a3301b",
 shopify_verified="Yes", shopify_evidence="Shopify Plus customer case study; on Shopify since 2014, uses Storefront API headless build",
 shopify_evidence_url="https://www.shopify.com/my/plus/customers/kotn",
 shopify_plus="Yes", shopify_plus_evidence="Shopify Plus customer page and Shopify enterprise blog 'headless architecture kotn'",
 operational_signal="Consolidated two stores into one headless storefront with custom checkout; 12 retail stores across Toronto, Montreal, Vancouver, NYC and LA; expanding into hospitality (hotel and store in London)",
 automation_opportunity="Potential opportunity: automating inventory and fulfillment coordination between the headless storefront and 12 retail locations across Canada and the US.",
 buying_intent="Medium",
 personalization_detail="Consolidated two Shopify stores into one headless storefront on the Storefront API with custom product pages and checkout",
 personalization_reason="Custom headless stack plus multi-country retail means integrations and back-office workflows need maintenance that automation can reduce",
 source_urls=["https://www.shopify.com/my/plus/customers/kotn","https://www.shopify.com/enterprise/blog/headless-architecture-kotn","https://ca.linkedin.com/in/rami-helali-18a3301b","https://canadianbusiness.com/people/kotn-co-founder-rami-helali/","https://www.theglobeandmail.com/business/article-canadian-retailer-kotn-makes-a-bold-move-into-hospitality/","https://www.blogto.com/fashion_style/2024/05/kotn-ossington-toronto/"],
 evidence_type="Shopify Plus case study; LinkedIn; Press article",
 research_confidence="High",
 notes="Certified B Corp. Website domain assumed kotn.com (brand name); verify before outreach."),
rec(company="Tentree", website="https://www.tentree.com", shopify_store_url="tentree-devstoreus.myshopify.com (dev store); https://www.tentree.com",
 country="Canada", industry="Apparel", product_category="Sustainable apparel",
 shopify_verified="Yes", shopify_evidence="Brand-tied myshopify domain (tentree-devstoreus.myshopify.com) indexed with tentree collections; Ecomx agency Shopify redesign",
 shopify_evidence_url="https://tentree-devstoreus.myshopify.com/",
 shopify_plus_evidence="Checkout upsell ('Protect Your Order + Plant 1 Tree') suggests Checkout Extensibility, but no Plus case study found",
 product_count_signal="'All Sustainable Items' collection paginates to page 151 on the brand's dev store",
 shopify_apps="Klaviyo (per Panoramata marketing profile)",
 operational_signal="Large catalog; separate US store instance (devstoreus); in-checkout tree-planting/order protection add-on; Shop Pay Installments",
 automation_opportunity="Potential opportunity: automating tree-planting impact tracking and order-protection claims tied to each checkout add-on.",
 buying_intent="Medium",
 personalization_detail="Offers a checkout add-on to 'Protect Your Order + Plant 1 Tree' for $4.50",
 personalization_reason="Per-order add-ons create claims and impact-reporting workflows that scale with order volume",
 source_urls=["https://tentree-devstoreus.myshopify.com/","https://tentree-devstoreus.myshopify.com/collections/all?page=151","https://ecomxagency.com/pages/tentree-s-transformation-with-ecomx-agency-s-shopify-redesign-expertise","https://www.shopify.com/enterprise/blog/checkout-pages","https://www.panoramata.co/marketing-strategy-brand/tentree","https://tentree.knoji.com/questions/tentree-shop-pay-installments/"],
 evidence_type="myshopify domain; Agency case study; Shopify blog mention; Marketing profile",
 research_confidence="Medium",
 notes="Canada is known HQ country but city/province not evidenced in results seen; left blank. Status not separately checked due to search budget."),
rec(company="Knix", website="https://knix.com", shopify_store_url="https://knix.com",
 country="Canada", industry="Apparel", product_category="Intimates and period underwear",
 shopify_verified="Yes", shopify_evidence="Shopify case study: virtual warehouse sale hosted 35,000 shoppers in 10 minutes",
 shopify_evidence_url="https://www.shopify.com/case-studies/knix",
 shopify_plus="Yes", shopify_plus_evidence="Shopify Plus customer page for Knix; case study built a separate Shopify Plus storefront for the warehouse sale",
 product_count_signal="Tens of thousands of items offered in virtual warehouse sale; bundles by size and fit",
 shopify_apps="Rewind Backups (per Rewind LinkedIn post)",
 operational_signal="Handled 5,000 simultaneous checkouts; runs separate sale storefront; thousands of virtual fittings per month; showroom stores; international expansion plans",
 automation_opportunity="Potential opportunity: automating virtual-fitting booking follow-ups and size/fit-based bundle inventory allocation.",
 buying_intent="Low",
 personalization_detail="Hosts thousands of virtual fittings per month with 97% of slots booked",
 personalization_reason="High-volume appointment scheduling and follow-up is a repeatable workflow well suited to automation",
 source_urls=["https://www.shopify.com/case-studies/knix","https://www.shopify.com/ng/plus/customers/knix","https://www.linkedin.com/posts/rewind-io_why-knix-uses-rewind-backups-for-shopify-activity-6521820866727288832-ynkb","https://www.shopify.com/blog/knix-changing-how-women-are-marketed-million-dollar-exit"],
 evidence_type="Shopify case study; Shopify Plus customer page; App vendor post",
 research_confidence="High",
 notes="Shopify blog references a 'million-dollar exit' (brand acquired); likely corporate-owned, hence Low intent. Warehouse sale traditionally in Toronto; HQ city not explicitly evidenced so left blank."),
rec(company="Mejuri", website="https://mejuri.com", shopify_store_url="https://mejuri.com",
 country="Canada", industry="Jewelry", product_category="Fine jewelry",
 prospect_name="Noura Sakkijha", first_name="Noura", job_title="Founder",
 contact_source_url="https://www.shopify.com/id/enterprise/blog/noura-sakkijha-on-how-mejuris-community-is-powerful-fuel-for-brand-loyalty",
 shopify_verified="Yes", shopify_evidence="Shopify case study and unified-commerce interview; Harley Finkelstein post 'Today, Mejuri is officially on Shopify'",
 shopify_evidence_url="https://www.shopify.com/case-studies/mejuri",
 shopify_plus="Yes", shopify_plus_evidence="Noibu case study on Mejuri's Shopify Plus migration",
 shopify_apps="Shopify POS; Noibu (per Noibu case study)",
 operational_signal="39 retail stores across US, UK, Canada and Australia; unified online and offline with Shopify POS; migrated to Shopify Plus",
 automation_opportunity="Potential opportunity: automating cross-border inventory balancing and in-store/online order exceptions across 39 stores in four countries.",
 buying_intent="Medium",
 personalization_detail="Runs 39 brick-and-mortar stores across the US, UK, Canada and Australia on Shopify POS alongside ecommerce",
 personalization_reason="Multi-country omnichannel operations create high volumes of inventory, returns and order-routing tasks",
 source_urls=["https://www.shopify.com/case-studies/mejuri","https://www.shopify.com/retail/mejuri-unified-commerce","https://www.shopify.com/blog/mejuri-unified-commerce","https://www.noibu.com/customers/case-studies/how-mejuri-navigated-their-shopify-plus-migration-with-the-help-of-noibu","https://www.linkedin.com/posts/harleyf_today-mejuri-is-officially-on-shopify-their-activity-7236793035173322752-9m-A","https://storeinspect.com/shopify-store/mejuri","https://www.shopify.com/id/enterprise/blog/noura-sakkijha-on-how-mejuris-community-is-powerful-fuel-for-brand-loyalty"],
 evidence_type="Shopify case study; Vendor case study; Tech profile; LinkedIn",
 research_confidence="High",
 notes="HQ city not evidenced in results seen; left blank. Founder title as described by Shopify blog (founded 2013)."),
rec(company="Peace Collective", website="https://peacecollective.ca", shopify_store_url="https://peacecollective.ca",
 country="Canada", state="Ontario", city="Toronto",
 industry="Apparel", product_category="Lifestyle and licensed sports apparel",
 prospect_name="Yanel Dhailieh", first_name="Yanel", job_title="Founder",
 contact_source_url="https://www.shopify.com/blog/peace-collective-viral",
 shopify_verified="Yes", shopify_evidence="Shopify blog feature on Peace Collective; Katana case study describing Shopify Plus integration",
 shopify_evidence_url="https://katanamrp.com/case-studies/peace-collective/",
 shopify_plus="Yes", shopify_plus_evidence="Katana MRP case study cites integration with Shopify Plus across multiple web stores",
 shopify_apps="Katana MRP (per Katana case study)",
 operational_signal="Multiple web stores; on-demand product range expanded 50%+; sports team and influencer licensing; US market expansion; manufacturing managed via Katana",
 automation_opportunity="Potential opportunity: automating licensed-product order routing and on-demand production handoffs across multiple Shopify Plus stores.",
 buying_intent="High",
 personalization_detail="Expanded its on-demand product range by over 50% with Katana, adding sports-team and influencer licenses across multiple web stores",
 personalization_reason="Multi-store, licensed, made-on-demand catalog multiplies SKU setup and fulfillment workflows",
 source_urls=["https://katanamrp.com/case-studies/peace-collective/","https://www.linkedin.com/posts/katanamrp_peace-collective-an-apparel-brand-based-activity-7191073868680179713-FyJx","https://www.shopify.com/blog/peace-collective-viral","https://www.shopify.ca/enterprise/how-brands-are-showing-support-during-covid-19","https://www.acceler8labs.com/case-study/peace-collective/","https://commercegarage.com/peace-collective-case-study/"],
 evidence_type="Shopify blog; Vendor case study; Agency case study",
 research_confidence="High",
 notes="Toronto per Katana LinkedIn post. Website domain assumed peacecollective.ca; verify before outreach."),
]
json.dump(R, open("/tmp/claude-0/-home-user-rappido/671930c5-e8f7-572b-8a98-f01973c2106a/scratchpad/batch1/seg6_ca_ie.json","w"), indent=1, ensure_ascii=False)
print(len(R))
